founders_online:   {license: "CC-BY-NC", include: true}
evans_tcp:         {license: "PublicDomain", include: true}
ecco_tcp:          {license: "PublicDomain", include: true}
american_stories:  {license: "CC-BY-4.0", include: true}
century_lawmaking: {license: "PublicDomain", include: true}
old_bailey:        {license: "CC-BY-NC", include: true}
